# Generated by Django 5.2.4 on 2025-07-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField()),
                ('sector', models.CharField(max_length=80)),
                ('financials', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
